# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c4185a6066f6f66be32c869954428f14eb53d0c9c6ff18238fb1285de1a437358da612c59b445a812c6faec2bde366bbda82751aa265246644072511de3526a

test:
  secret_key_base: 50cf4fc8c76a0515f8282d62cb3b1c594853646d6570103138c530f6d92a5461fe6b429683f6e6d974ff8f06227ac4f2027ba68edd642034c62e03136a526852

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
